### ISSUE TITLE
Consider changing display of charts in surveys dash to make small changes more visible

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#1019]
Several of the surveys signals change on a very small scale, and recent trends are muted or invisible when using a 0-anchored y-axis. We want to consider the following changes:

* switch the default display to have "Re-scale Y axis" turned on
* make uncertainty explicit using error bars / shaded region showing stderr

0-anchored Y axes are accepted best practice for bar charts, but for line charts, recommendations vary. In the case of the survey signals where small changes in public opinion or behavior may have larger effects on public health, it makes sense to zoom in to make these small changes more visible by default.

Adding in the stderr will help prevent overamplification of trends/noise.

**Additional context**

Before we go through with this change, we need to review the stderr computation of non-CLI/ILI survey signals to make sure they are correctly accounting for survey weights.

**Comment by ryantibs** [comment]
Thanks Sam.  Few things: 

1. Can we change the "Rescale Y-axis" toggle to say something like (for example) "Include 0 in Y-axis", and then set it to be "off" by default.  (Same effective behavior, just different name.)
2. The plot titles look off from the live version.  For example, I see the word "(Weighted)" in the plot title now in a bunch of places (attached screenshot is an example), where I don't see this in the live version.  Is this a bug or just something that will be automatically fixed in the live version?  
3. In the attached screenshot, the y-range isn't being properly computed.  Perhaps it has something to do with missing values?

<img width="614" alt="Screen Shot 2021-09-25 at 10 57 13 AM" src="https://user-images.githubusercontent.com/732541/134775963-fa1e00ea-4ce4-451d-9fe0-e38c9ebfd1a2.png">

**Comment by ryantibs** [comment]
@capnrefsmmat While I'm on this PR.  The standard errors are actually pretty big in a few places (for example, see screenshot) which I was happy to see.  In other places, not so big.

How hard would it be just to update the way we compute weighted standard errors?  Since it's just a plug-in estimate of standard deviation for a binomial (outside of the CLI signal)?  Can we fix this ASAP, or am I missing something?

<img width="606" alt="Screen Shot 2021-09-25 at 10 56 48 AM" src="https://user-images.githubusercontent.com/732541/134776088-88a51c9f-acdd-40f4-b03a-874861660ad9.png">

**Comment by capnrefsmmat** [comment]
> How hard would it be just to update the way we compute weighted standard errors? Since it's just a plug-in estimate of standard deviation for a binomial (outside of the CLI signal)? Can we fix this ASAP, or am I missing something?

We can easily update the code (well, after verifying we have the math correct and testing it), but the problem here is updating all the standard errors we've already issued in the past. Since the weighted standard error depends on the weights, we can't simply run a SQL query on the database to apply a transformation to the weights; we'd need to regenerate every value of every signal. To do that *and* preserve the issue history would be extremely difficult.

So we have a few options:

1. Change how the code generates standard errors but don't reissue past data; all standard errors after a certain issue date will use the new method, the rest will remain with the old method.
2. Reissue past dates but keep older issues of those dates. The complete history of each signal is available with the right SEs, but older issue dates have the previous SEs.
3. Reissue past dates and nuke old issues of those dates, so the only available estimates have the right SEs.
4. Spend a great deal of time figuring out how to reconstruct the entire issue history with the correct SEs.

For reference, I'd expect standard errors to inflate by a factor of about 1.2 - 1.5 as a result of calculating the weighted estimates.

Note that this problem is easier for our [contingency tables](https://cmu-delphi.github.io/delphi-epidata/symptom-survey/contingency-tables.html), because we don't provide an issue history for them; we can just apply the change there and reissue all the data.

**Comment by sgratzl** [comment]
re changing computation of stderr: can we move this discussion an issue in a different repository, please. it will be lost and forgotten here
