### ISSUE TITLE
Doctor Visits indicate uncertainty in recent values

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#1050]
I would like to make it graphically clear, at least until we start publishing backfill-corrected signals, that recent data from the doctor visits signal is subject to considerable backfill.  

We can do this by plotting the last 10 days as a dotted line, or using a shaded background for it, or both.   

The plot below, which comes from the indicator status page, shows that data between 0 and 10 days lagged is often subject to a relative error of +/- 5%.  So I think we should use this as the time window to modify the plot (dotted line, and/or shaded region), and explain why we're doing this.

**Comment by ryantibs** [comment]
The message above was copy-pasted from what I wrote in our working google doc about the dashboard redesign.  Here is the plot that I was referring to:

![Screen Shot 2021-11-09 at 9 44 55 AM](https://user-images.githubusercontent.com/732541/140945465-93b25db0-3d91-4f33-9cf0-afe3520d23e3.png)

**Comment by ryantibs** [comment]
@sgratzl Finally getting back to this ... What is the particular feedback you're looking for here?  

Can you implement a mock up of what I suggested above: wherever we plot the doctor visits signal in a time series plot (on its own indicator page), can you put a light gray region that shades the background, from current-date - 10 through current-date?  And draw the signal curve as a dash line in that region?

Then we draft some text to appear in a footnote below the plot explaining that the last 10 days are typically subject to heavy backfire. If that text can be pulled from some spreadsheet (like a lot of the other tools tips and labels are?) then it would also us to directly wordsmith it.

Tagging @RoniRos @rumackaaron.  I chose this solution in an ad hoc fashion, with the idea that something is better than nothing.  If you want to suggest a way to tweak/edit it (but still keep it manual for simplicity) then please suggest it ASAP.  Aaron, if you want to take over advising on the specifics here (both of the numbers and the language) then I would also be happy with that.  (Note: only the doctor visits signal appears on the main dashboard at this point, and not any CHNG-based ones, so this is the only one we need to do this for.)

Sam: if this takes too long to resolve then we shouldn't let it hold up v3.  I want to close in on that ASAP since we've been sitting non it for a while.  We can always solve this later and update the dashboard when it's ready.
