### ISSUE TITLE
Inconsistency and/or lack of clarity in date definition on COVIDcast dashboard

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/www-covidcast#1143]
When pulling down the date chooser, it says "the most recent available date is X, available on Y".  

1. In the example below, this appears incorrect: X=Jan 13, Y=Jan 18, but data seems available thru Jan 14.  This seems to be the case for many examples.

2. Even when the date is correct, the above quoted sentence is not as clear as can be.  How about something like:
      "Data is available for dates up through X (last updated on Y)"

![image](https://user-images.githubusercontent.com/23179630/150201441-25ca4e8a-62e6-45d3-ab61-b19963e0afdd.png)

**Comment by RoniRos** [comment]
Yes, both the incorrectness, and the lack of clarity re ref date vs. report date.

**Comment by krivard** [comment]
@sgratzl I could've sworn this got fixed in #1127 but it looks like the calendar caption is computed elsewhere. 

nb Roni's screenshots are from 3.0.0 but this problem persists in 3.0.1 (released this afternoon)

1. Go to [https://delphi.cmu.edu/covidcast/?date=20220118](https://delphi.cmu.edu/covidcast/?date=20220118)
2. Tooltip is correct (most recent Jan 18/last update Jan 18)
3. Calendar caption does not match (most recent Jan 17/updated on Jan 18)

![image](https://user-images.githubusercontent.com/1158666/150217187-e9f1e3cc-808e-4fff-ba8f-838701e7978f.png)

@RoniRos here's a mock of your recommended edit:

![image](https://user-images.githubusercontent.com/1158666/150217708-be8b24eb-7669-43b3-a5fe-fbc1ff760257.png)

still good?

**Comment by sgratzl** [comment]
yes it is related. So far I manually implemented workarounds but not a permanent fix, since the meta data is just behind the real data.

**Comment by RoniRos** [comment]
> since the meta data is just behind the real data.

Ouch.  Do we know why?  Are there plans to fix it?
