### ISSUE TITLE
consider switching to TypeScript

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#380]
It would be great if the code bases switches to TypeScript for a better code base and earlier error detection. Over the last month I added more and more TypeScript like comments which already improves the code completion but switching to TypeScript would work better. 

see also https://svelte.dev/blog/svelte-and-typescript

**Comment by dlaliberte** [comment]
I support the idea of migrating to TypeScript.  Depending on the build environment, it can be done incrementally since TypeScript is pretty much a superset of JavaScript.   Migrating to TypeScript can be a chore, however.  Tools make it easier, but there are many decisions to be made about exactly how to clean up the mess that JavaScript allows, and sometimes difficult refactorings are required, e.g. to break circular dependencies.

It seems clear to me that TypeScript is definitely the future of JavaScript.  I will not be surprised if all browsers support TypeScript in a few years, perhaps via compilation in the browser to WASM.   Or maybe the ES-series enhancements of JS will migrate incrementally toward TypeScript.

**Comment by sgratzl** [comment]
FAQ to svelte + TS: https://svelte.dev/faq#what-about-typescript-support

eslint + svelte + TS: https://github.com/sveltejs/eslint-plugin-svelte3/issues/68 ... seems to be a problem

**Comment by tildechris** [comment]
Let's close this for now.  Until this is well-supported, it may give us more headaches in the short-term than benefit.
