### ISSUE TITLE
color scales ranges

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#394]
**Actual Behavior:**

Roni:
> Case colors are too heavily in the dark range, most extremely in (Cumulative, Ratios) mode – does the color scale need to be adjusted?

![image](https://user-images.githubusercontent.com/4129778/91426689-2515a700-e85d-11ea-891b-48ef3766d360.png)

**Comment by dlaliberte** [comment]
How about a color scale that has more variance at both the high end and low end, like an S-curve?    Doesn't help with animation, however, since the low variance middle area will have to be crossed at some point.

Having consistency over time conflicts with rescaling to better show differences at each time.  But how about showing both a global scale (across all time) and a local scale (for the current time), so the user could select which scale they want to use.  Also, the local scale could be resized to show how it relates to the size of the global scale.  Something like this:

all time scale:  [0 ...                     |                             |       max over all time]
current scale:                              [1K...   10K... 100K]

You'll have to imagine the gradient of colors inside the [brackets...].

**Comment by RoniRos** [comment]
As hard as this problem is, here is making it harder: 
Beyond the need to highlight _relative_ _differences_ between different locations (and to some extent also across time), for many signals it is important to show the _absolute significance_ of the current levels:  North Dakota may have the highest number of tests each day, but is it really that high?  Or, Iowa may have the lowest, but is it really very low?  For many of our indicators, there are some a priori reference points, expectations, desiderata, or red lines whose crossing is significant.  Arguably, we should not use "hot red" to indicate a level that is not disconcerting, or green to indicate a level that it totally fine, regardless of the levels at other locations.  For some signals, it's not about the boundary between "good" and "bad", but about comparison to familiar markers (like, e.g. pre-pandemic levels).
Suggested solutions are hereby solicited.  
In a time plot context, one or more horizontal lines may convey that reference information.

**Comment by dlaliberte** [comment]
We could visualize a quantifiable measure of significance itself, perhaps with another attribute such as line thickness, or opacity, or with a separate indicator analogous to confidence bands.  Or we could flag significant events with annotations, if they have a discrete time or place to flag.  Annotations can highlight ranges or areas as well as points.

Letting the user infer significance, particularly if it is subjective, means we have to show enough so they can do that inference, such as showing a values relative to a total, or relative to arbitrary thresholds.    We can show both absolute values and relative values (e.g. per-capita) in the same chart if we avoid the confusion of multiple scales.   We can show both values and change of values (1st derivative, 2nd derivative...) in the same chart more easily since they have the same scale, but again, we have to be careful when showing the rate of change (which is relative).

**Comment by dlaliberte** [comment]
If we start to use colors more consistently to represent "good" or "bad" things, then we should be careful to be comprehensive so that we don't leave out a few cases that accidentally imply the opposite of what we intend.

Also we ought to be careful of cultural assumptions about color.  "Red" is not bad everywhere, nor is "green" always good.

**Comment by RoniRos** [comment]
> If we start to use colors more consistently to represent "good" or "bad" things, then we should be careful to be comprehensive so that we don't leave out a few cases that accidentally imply the opposite of what we intend.
Can you explain or give an example?

> Also we ought to be careful of cultural assumptions about color. "Red" is not bad everywhere, nor is "green" always good.
Fair point, although we are optimizing for U.S. consumption.

**Comment by dlaliberte** [comment]
> > If we start to use colors more consistently to represent "good" or "bad" things, then we should be careful to be comprehensive so that we don't leave out a few cases that accidentally imply the opposite of what we intend.
> 
> Can you explain or give an example?

I just mean that "starting to be consistent" is not the same as "being consistent everywhere".  But there are also probably cases where we are not sure whether to consider a high value for some indicator either good or bad.  Maybe more visits to hospitals correlates with more infections, for example.

**Comment by capnrefsmmat** [comment]
The "define thresholds for good or bad and map that way" strategy is what sites like [COVID Exit Strategy](https://www.covidexitstrategy.org/) do. It makes sense for their mission and target audience: their audience wants to know "How bad is my state?" and they can answer "Bad", supplementing that with the tables showing each metric color-coded by some standard.

On the other hand, our approach right now seems more designed for people who want to compare specific metrics in ways we don't anticipate. Since they're sophisticated and we don't know their exact criteria, we instead present all the data in ways that facilitate the user drawing their own conclusions.

I think both approaches have merit for their audience. But we need to decide who our audience is so we can understand which approach better serves their needs; and if we decide on setting good/bad thresholds, we'll have to talk to the audience to figure out what is good and what is bad.

**Comment by RoniRos** [comment]
I very much agree that the specifics should depend on who the users are and what they want.
But for now, we continue to develop for an ill-defined, general, user, which appears to be at least moderately data savvy.
My suggestion was _not_ to switch to the CAN style, but rather to add some absolute grounding to some of the signals.
The main goal continues to be geo-wise and time-wise comparisons.  But for the same relative comparison of locations, there is a significant difference between, say, most of them being "not-too-bad", and all of them being in pretty bad state.  I was suggesting that we try to convey that sense.

Here is one concrete suggestion, not necessarily the best one:  add one or more reference points to the color _legend_.  E.g. ads a small tick on the color legend itself and indicate that it corresponds to the 'pre-pandemic level', or to the 'threshold for opening the economy', or some such thing.

**Comment by ryantibs** [comment]
I think I'm also going to close this because this is a very static issue at this point. For example, we recently redesigned/extended the color scales during Omicron first wave, so at least this is out of date with what we presently have. We can always bring it back to life if somebody tells me I'm wrong.
