### ISSUE TITLE
define which geo level to use for scales

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#482]
for e.g. doctors visits only one scale (mean, stddev) independent of the geo type (state, county) is used. 

However, taking a look at the code it is not defined which geo type that is, it seems to use the first one coming back from the api, which is unreliable:

https://github.com/cmu-delphi/www-covidcast/blob/ef598a313df7b632b795c202c5d55f3f52d987ad/src/data/index.js#L66-L82

possible options:
 * use counties as reference
 * use the maximal one (defined by mean)?
 * use an average?

**Comment by tildechris** [comment]
@krivard is this something that should be addressed in the API?

@sgratzl this information is used to generate color scales, correct? Are there other aspects that uses these stats?

**Comment by sgratzl** [comment]
> @sgratzl this information is used to generate color scales, correct? Are there other aspects that uses these stats?

yes, the mean/stddev is used to define the color scale domain and also for now the y-scale in the top 10 view

**Comment by krivard** [comment]
@tildechris this seems to stem from a disconnect between what the metadata signal provides (mean/stdev for each source X signal X geo level) and what the map is trying to use it for (sensible scales for each source X signal, irrespective of geo level). It's not clear this should be handled within the API, but if we wanted to do something there, here are two options:

* Add an extra record to metadata with `geo_type:*` stating mean/stdev for all geo levels within a signal
* Add an extra field `num_entries`/`sample_size` to metadata so that it's easier to generate mean/stdev of combinations of geo levels on the client side using weighted averaging
