### ISSUE TITLE
add download options to detail views

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#484]
It would be great if the vega views (such as the detail view) has a download option in PNG or SVG format. Since both are a standard feature of Vega it should be a simple one. 

![image](https://user-images.githubusercontent.com/4129778/94132415-926a2700-fe5f-11ea-8ff7-d615b1ce561a.png)

e.g. a start is in 

https://github.com/cmu-delphi/www-covidcast/blob/ce717edd3ec89a78e56c6a6e7ab4e9ac6149d15a/src/components/DetailView/DetailView.svelte#L149-L156

**Comment by dlaliberte** [comment]
I can do this.  I don't see how to assign myself, however.  The "Assignees" header above doesn't have any option under it even though I am logged in to GitHub.

**Comment by dlaliberte** [comment]
> the code snippet refers to an outdated branch of mine: #419 If you take a look at the code it should explain them.

I get it now.  The file link would have taken me there, though there is no clue about the code branch in the visible text of the link.  That's where I can also find the missing screenshot.js.  OK thanks!

**Comment by dlaliberte** [comment]
The download button has been added.  However, one additional change should be made to move the title to the chart itself, so that it ends up in the image that is generated.   Currently we display the title outside of the chart, in HTML, which means that the image generated from the chart will have no title.  

The complication is that the title is followed by the two buttons, one for the '?' to get additional information, and now one for the save icon (the floppy disk).   If they stay in HTML, positioning them after the title will be difficult if the title is not in HTML, but displayed by the chart.    We could instead move those buttons to be up near the close button (the 'X') in the corner.

**Comment by dlaliberte** [comment]
I'm not sure whether I can made additional changes (for a new pull request) on the same branch I used before: cmu-delphi/dlaliberte/#484.  I'll have to create this as a new branch in my local repository because I had to trash the previous one.  I expect it will be the same remote branch.  Seems like it should allow multiple changes on the same branch, but who knows.
