### ISSUE TITLE
Adjust y-axis on mask data to better fit data spread

### ISSUE THREAD

**Issue by philmcguinn** [cmu-delphi/www-covidcast#618]
**Actual Behavior:**

Mask data in charts is displayed on a 0% to 100% scale, squishing the data down to a fraction of the available area and thus making it hard to read

When I...

View mask data in the COVIDcast visualization, top 10, possibly more

1. go to https://covidcast.cmu.edu/?sensor=fb-survey-smoothed_wearing_mask&level=county&date=20201102&signalType=value&encoding=color&mode=top10&region=55087
2. use eyes to view masks signal

**Expected behavior**

Mask data would be displayed on a more appropriate scale. I would suggest going from 50 or 60% to 100% at least, or if we want to get fancy consider doing, say, 2-3x the difference from highest to lowest value in the current dataset (so if the spread is 3%, show 6% or 9%). This could be tricky since we could make small differences seem large if we make the scale too small.

**Screenshots**

![Screen Shot 2020-11-06 at 8 26 00 AM](https://user-images.githubusercontent.com/71901127/98390862-c615a080-200a-11eb-8e5f-86ccc84a8a07.png)

**Rating Scale (1 is minor, 7 is severe):**

2

**Context**

- Browser: Chrome

**Additional context**

n/a

**Comment by dlaliberte** [comment]
Interesting suggestion.  

We do already adjust the max of the y-axis to avoid leaving empty space above the data.  We are explicitly using 0 for the min of the y-axis, though it does have this effect of compressing the data to the top, if it is all close to the max.

The top-10 charts use to clip the data on the top, but now, we avoid any clipping on the high side by iterating over the data for every location to find the maximum across the entire timespan.  But I am making a change to limit the timespan to a smaller subset, so that the time around the currently selected date is less compressed.   Showing the clipped region clearly is part of the puzzle.  See #507 and #589 for discussion on this.

So this suggestion means we are doing something similar on the low side, but doing this raises the question whether we should similarly clip lines on the low end, if they are outside of the neighborhood of the current date.

**Comment by sgratzl** [comment]
from a visualization point of view it is highly encouraged to start a value axis with 0. Otherwise, you skew the perception of the absolute values. If we wanna go in this direction we might not show the y-axis (the axis and its ticks) at all and just show it as a sparkline. 

re value range: for coloring the map there is already a similar thing is place. the start/end values are `mean +- 3 * stdev`: 
![image](https://user-images.githubusercontent.com/4129778/98398846-97f68780-202f-11eb-91b9-904283716362.png)

**Comment by capnrefsmmat** [comment]
There's also the option of some kind of rescaling. The New York Times map over the summer plotted the probability that, in five different encounters, everyone would be wearing a mask; that would exaggerate differences and pull a lot of the numbers down closer to 0. Maybe we could do a similar rescaling, like "the probability that 5 people would wear masks most or all of the time" (`signal^5`).

**Comment by dlaliberte** [comment]
Regarding skewed perceptions, a similar skewing happens if percentage values are all small, say less than 5 percent, but we don't show the full axis up to 100%.  

But I think that if expectations are that a set of values ought to be all low (or all high) then it is reasonable to be able to zoom in to the area of interest and not show the full axis.  But I think it is important to somehow emphasize that the axis is truncated.

**Comment by tildechris** [comment]
Let's close this for now.  We'll continue to address the y-axis scale issue in the redesign.  There are a few proposals that give us quality improvements.
