### ISSUE TITLE
X-Range should persist across selection

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#623]
Re: #619

When using the large time series chart, one can use the date range widget to change the range of the plot:

![image](https://user-images.githubusercontent.com/46794497/98861364-248bb600-2433-11eb-95e6-73e5c42ef77f.png)

Currently if you add another area to the selection, this date range gets reset, causing the user to have to navigate back to the area they found interesting.

We should persist the current date range across geo selections to improve this behavior.

**Comment by dlaliberte** [comment]
Probably should also preserve the date range when changing indicators as well.

But once we are preserving the date range everywhere we should, then we may need an easy way to reset to the full date range.

I'd also like to make the date range editable, by dragging one end or the other, rather than dragging the entire date range, or restarting with a new date range if you click outside of it.   But that is another issue (that will be fun to work on).

**Comment by dlaliberte** [comment]
Ignore that erroneous mention relative to Dlaliberte/details2 #640
No idea why GitHub offered to do a pull request for what I had already created a pull request for, and then it turned around and said "there is already a pull request for that".

**Comment by dlaliberte** [comment]
Closing the Detail View and opening again will restore the default date range to the small multiple time span.  That seems like a reasonable compromise for now.  We could persist the date range selection longer, but would need some way to reset it.
