### ISSUE TITLE
Y-axis label doesn't differentiate between counts and ratios

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#625]
Re: #619 

> When I toggle between incidence/cumulative and counts/ratios (per 100,000) the y-label on the big time series plot remains the same. It should change. Certainly when you toggle between counts/ratios, it's no longer correct to label the y-axis "Cases" or "Deaths" for example, it should say "Cases per 100,000" or "Deaths per 100,000".

Fix the y-axis label so that we are being precise with the units that we are showing.

**Comment by dlaliberte** [comment]
Here is my first quick rendering of a more correct label.   I just added a parenthesized qualifier of what kind of "Cases" it is.  

Incidence + Counts
![image](https://user-images.githubusercontent.com/570125/99096268-14dfaf00-25a4-11eb-9e33-da2401b2cba1.png)

Incidence + Ratios (per 100,000)
![image](https://user-images.githubusercontent.com/570125/99096496-540e0000-25a4-11eb-936c-a52399d2c2b3.png)

Cumulative + Counts   (also notice the title cut-off on the left)
![image](https://user-images.githubusercontent.com/570125/99096716-9df6e600-25a4-11eb-9f9f-9188b912e127.png)

Cumulative + Ratios (per 100,000)
![image](https://user-images.githubusercontent.com/570125/99096868-d39bcf00-25a4-11eb-8d84-febda7f8aeff.png)

**Comment by dlaliberte** [comment]
@ryantibs - you said for Cases with Ratios, should say "Cases per 100,000", but what about the Cumulative Counts and Cumulative Ratios?

**Comment by capnrefsmmat** [comment]
I believe all of them are calculated per 100,000 population.

**Comment by dlaliberte** [comment]
The Counts are not per 100,000, but absolute numbers.  I'll go with these four:

1. Cases
2. Cases per 100,000
3. Cumulative Cases
4. Cumulative Cases per 100,000

**Comment by dlaliberte** [comment]
I just noticed another problem with the Detail View charts.  The first line of the title is always the name of the indicator on the _map_ but not (necessarily) the one in the chart.  This is just wrong and misleading, since the detail chart has nothing to do with the map indicator.  The first line also says "... in location, location, location" for all the locations in the chart.  The second line gives the correct name of the indicator.  

So I can change the title to put the indicator name first, and move the "... in location..." to the second line, like so:

![image](https://user-images.githubusercontent.com/570125/99118717-030f0380-25c6-11eb-8e42-607bc075a48d.png)

But notice also that the buttons on the right will be on top of the title, if the title is too long.  Making this indicator name be the second line avoids the overlap, but we would have to start with "In location, location, location ...".

**Comment by ryantibs** [comment]
Thanks @dlaliberte for the update and sorry to be late to the party.  (And good catch with the subtitle in the last comment!  Important to fix that.)  As for the y-axis label, I think the best choice is just to put: 

1. Cases
2. Cases per 100,000 people

for counts and ratios, respectively.  Not the use of "initial caps" and not "title caps", which is consistent with the way we've been labeling everything so far (I believe).  And to be clear, I would use these labels for *both* incidence and cumulative.  Because the title very clearly says "Newly reported COVID-19 cases ..." for incidence, or "Cumulative reported COVID-19 cases ...", and what the how you'd interpret the *units* of the y-axis is actually still the same thing in either setting, which is "Cases" or "Cases per 100,000 people".

Some more nitpicks (copyediting type comments) cc @RoniRos @capnrefsmmat who also tend to care about these things :).  Pasting a screenshot below to set the context for the nitpicks

<img width="876" alt="Screen Shot 2020-11-13 at 11 13 20 PM" src="https://user-images.githubusercontent.com/732541/99139380-03c78a00-2606-11eb-95c3-08ba72db3072.png">

- In the 4-way toggle button, we should probably call it "New" rather than "Incidence".  This is because "Cumulative" is an adjective, and "Incidence" is a noun.  So we could use "Incident", but "New" is probably more universally understandable, and AFAIK, we use "New" in all the titles everywhere anyway.

- When in cumulative mode, the legend still says "daily new COVID-19 cases", which is obviously wrong.  And also in incident rate mode, the legend still says "daily new COVID-19 cases", which is again wrong.  How about simply calling this "Raw data"?  (Note the initial caps again.)  If not we just have to make sure this matches all the setting appropriately.

- In the mouse-over, can we just say "7-day average" rather than "7-day avg"?  We clearly have the space on that line, and AFAIK, we're not using "avg" anywhere else.

As I flip through the rest of the map with my nitpick goggles on, I'm now seeing a bunch of small things like this that are inconsistencies: we use title caps sometimes, initial caps other times.  And in some cases we don't appear to follow title caps in the standard way: like in the menu bar "Away from Home ...".  Most title caps style AFAIK recommend capitalization a preposition like "Away From Home ...".  Question for @RoniRos @tildechris: is it worth doing an "audit" to catch these inconsistencies and fix them?  Is this something @Akvannortwick could do?  Or should we just forget it?

**Comment by capnrefsmmat** [comment]
> And in some cases we don't appear to follow title caps in the standard way: like in the menu bar "Away from Home ...". Most title caps style AFAIK recommend capitalization a preposition like "Away From Home ...".

Nitpicking the nitpick: My *Garner's Modern American Usage* says

> When using up-style headings, capitalize the first and last words and all other words except for articles, conjunctions, and short prepositions (usually fewer than five letters).

I think "Away from Home" is hence fine.

The recommendation is also "Up-Style Headings: Avoid them." So maybe we can standardized on initial caps in most places, except menus of short headlines like the signal/source selector where title case makes the most sense.

**Comment by ryantibs** [comment]
Thanks @capnrefsmmat.  I'm truthfully fine with anything as long as we are 1. rigorous and 2. consistent.

Can't resist.  This is just being silly.  But nitpicking the nitpicking of the nitpick: as much as you can trust a website called capitlizemytitle.com, this reveals that "Away From Home ..." is consistent with APA, AP, MLA, NY Times, Wikipedia styles, and "Away from Home ..." is consistent with Chicago.

**Comment by ryantibs** [comment]
In conclusion, back to reality, I'd be happy to either @capnrefsmmat or @Akvannortwick or both (pending any strong opinions from other that we haven't heard) run an audit over the site and just make sure we adhere to a single, consistent style.

**Comment by dlaliberte** [comment]
Thanks guys.  I've updated the PR to include your suggestions, except I have done nothing (yet) about any of the initial vs title caps.   See [https://deploy-preview-633--cmu-delphi-covidcast.netlify.app/](https://deploy-preview-633--cmu-delphi-covidcast.netlify.app/)

**Comment by dlaliberte** [comment]
> I just noticed another problem with the Detail View charts. The first line of the title is always the name of the indicator on the _map_ but not (necessarily) the one in the chart. This is just wrong and misleading, since the detail chart has nothing to do with the map indicator. 

I was wrong about the title line.  It only happens to be the map indicator sometimes.  It's whatever the _first_ detail view had, because it wasn't reactive to the change. So this is easy to fix by just making it reactive.

**Comment by tildechris** [comment]
> is it worth doing an "audit" to catch these inconsistencies and fix them?

Yes, this is worth doing an audit.  We should pick a style guide and stick with it.  I'll open a separate issue for the audit and follow-up with @Akvannortwick.

**Comment by dlaliberte** [comment]
Another thing to add to the audit: [incidents vs incidence](https://www.grammar.com/incidents_vs._incidence)

**Comment by dlaliberte** [comment]
This much is done (except any initial vs title caps tweaks).  More to follow re: Comprehensive, consistent labeling of Cases and Deaths re incidence/ratios/cumulative #642
