### ISSUE TITLE
Allow users to compare different counties (easily)

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/www-covidcast#626]
This was a suggestion provided through user feedback, documented, I believe, by @philmcguinn here: https://docs.google.com/document/d/1A76kDOGFsNkRkDeKfCq1AJv3svGBjn4erFeSl-y2Diw/edit#

I happened upon it by chance and was very glad to have read it.  It provides a great case study of somebody who has made great use of our tools.  

One of his feature requests / pain points:

> Ability to choose more than one area to do side-by-side comparisons.  I usually just screen grab and build my own comparison charts.  For example, I hand-built a chart showing the deaths/100K for all the counties in PA - very informative.

I think this is a **low hanging fruit**, because (it appears) we already have most of the code written: for our "Top 10" tab: https://covidcast.cmu.edu/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201107&signalType=value&encoding=color&mode=top10

It would seem that we could reuse the "Top 10" tab but simply allow the user to search for and add an arbitrary number of counties.  After all, in the current functionality, a user may search for a location, which appends that location after the Top 10.  But searching for another location replaces the previously-searched-for one.

![Screenshot from 2020-11-11 15-52-48](https://user-images.githubusercontent.com/8422804/98863185-007da400-2436-11eb-9cc6-61670efd99bb.png)

**Comment by philmcguinn** [comment]
Hey Addison! Glad that was useful, though the file is only under my name because I copied/pasted an email from back in August. Given the timing, his needs might not be the same. When I interviewed Bill again recently, viewable [here](https://docs.google.com/document/d/1T-nKw6rQUwjzTrOEtdl6xBXzATEfecTC_XP-GBInyAs/edit?usp=sharing), he seemed to have good luck comparing counties using the functionality on the main map that was added since the prior interview.

That said, I like the overall idea of making a more customizable compare mode on a dedicated page, since it's so information dense on the mapping page. I could see "Top 10" being one option on a tab dedicated to comparison of counties across a particular factor, instead of having a dedicated Top 10 tab.

**Comment by huisaddison** [comment]
Cool!  The leads can prioritize this however they like - it just seemed like a logical feature to build out :)

**Comment by tildechris** [comment]
> For example, I hand-built a chart showing the deaths/100K for all the counties in PA - very informative.

@huisaddison, can you attach the chart that you built here?  That would be a good illustration of what you'd like to see.

**Comment by huisaddison** [comment]
@tildechris I quoted that from an interview -- but it looks like compare mode has already been built!  :) Closing the issue.
