### ISSUE TITLE
Region comparison mode constantly resizes while hovering values

### ISSUE THREAD

**Issue by philmcguinn** [cmu-delphi/www-covidcast#637]
**Actual Behavior:**

When doing a comparison in the "Region" tab, hovering a graph changes the numbers above the graph constantly and creates a very shaky visual

When I...

**Steps to Reproduce the Bug:**

1. go to https://covidcast.cmu.edu/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201113&signalType=value&encoding=color&mode=single&compare=06075&region=41940
2. Hover the COVID Like Symptoms in Community graph from left to right

**Expected behavior**

Graphs and charts would have appropriate sizing to avoid rapid resizing while hovering

**Screenshots**

n/a, it's motion not a static image

**Rating Scale (1 is minor, 7 is severe):**

3 - it makes the comparison mode difficult to use

**Context**

- Browser: Chrome

**Additional context**

n/a

**Comment by dlaliberte** [comment]
This problem is at least partially fixed in the development branch, and will be available in the next release.  See e.g. 
https://deploy-preview-633--cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201113&signalType=value&encoding=color&mode=single&compare=06075&region=41940

There is more that can be done to stabilize the table layout.

**Comment by philmcguinn** [comment]
Certainly looks better in that version, still a bit jumpy but not headache-inducing 👍

**Comment by dlaliberte** [comment]
I merged in more changes to reduce tooltip-related flickering.
