### ISSUE TITLE
"About this indicator" is disguised as a footer

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#779]
The “About this indicator” box uses a darker, full-width background: 

* [Link](https://deploy-preview-769--cmu-delphi-covidcast.netlify.app/indicator/?region=42003&date=20210225&sensor=fb-survey-smoothed_covid_vaccinated_or_accept)

![image](https://user-images.githubusercontent.com/1158666/109986404-b3b72500-7cd3-11eb-9404-5c0d10c3aa2a.png)

This fools my hindbrain into thinking that it’s a footer. This is not ideal, since that tells me that (1) there’s nothing below it and (2) none of the content in it is relevant to my current task, which are both false. 

Not sure what to recommend here, it’s _pretty_ but it makes my brain lie to me.

**Comment by tildechris** [comment]
@Letsgohyde should there be a visual distinction that there is content below that section?

**Comment by Letsgohyde** [comment]
Hey guys, I proposed we swap out the bg color to a lighter shade of gray with back text. 
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2513%3A435

I don't think we need a affordance to show there's more below.

**Comment by tildechris** [comment]
I think the concern is that the style has a 100% width just like many footers.  If it didn't go all the way across I like the current dark contrast scheme. Maybe we should use a card instead of a full width block?
Desktop:
![image](https://user-images.githubusercontent.com/46794497/110543687-a0072680-80f8-11eb-958d-723d7233ab76.png)

Mobile:
![image](https://user-images.githubusercontent.com/46794497/110543740-b3b28d00-80f8-11eb-8d08-2e22d6f631bf.png)

**Comment by Letsgohyde** [comment]
@tildechris yeah, I think that works. Here's a spec with that styling:
Desktop:
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2513%3A11
![image](https://user-images.githubusercontent.com/7318770/110577412-75789600-8117-11eb-8641-c1d39e3fa936.png)

Mobile: 
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2513%3A435
![image](https://user-images.githubusercontent.com/7318770/110577500-9e009000-8117-11eb-8295-1ba41796d593.png)

@sgratzl for visibility :)
